from .tools.pen_settings import PenSettings
from .project_tabs import ProjectTabs
from .tools.text_settings import TextSettings
from .tools.filters import Filters
from .tools.effects import Effects
from .history_map import CircleCanvas
from .layer_widget import LayersWidget
from .history_widget import HistoryWidget
from .toolbox_widget import ToolboxWidget
from .starter_window import *
from .main_window import *
